#!/bin/bash

payment_preimage="0x$(openssl rand -hex 32)"

# 0.01 CKB
response=$(curl -sS --location 'http://127.0.0.1:8233' \
    --header 'Content-Type: application/json' \
    --data "$(
        cat <<EOF
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [{
        "amount": "0xf4240",
        "currency": "Fibt",
        "description": "test invoice generated by node b",
        "expiry": "0xe10",
        "final_cltv": "0x28",
        "payment_preimage": "$payment_preimage",
        "hash_algorithm": "sha256"
    }]
}
EOF
    )")

echo "$response" | jq -r '.result'
invoice_address=$(echo "$response" | jq -r '.result.invoice_address')

curl -sS --location 'http://127.0.0.1:8231' --header 'Content-Type: application/json' --data "$(
    cat <<EOF
{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "send_payment",
    "params": [{
        "invoice": "$invoice_address"
    }]
}
EOF
)" | jq -r
