#!/bin/bash

PORT=8236
ip="43.198.254.225"

response=$(curl -s -X POST "http://$ip:$PORT" \
    -H "Content-Type: application/json" \
    -d '{
          "id": 1,
          "jsonrpc": "2.0",
          "method": "node_info",
          "params": []
        }')

f_peer_id=$(echo "$response" | jq -r '.result.peer_id' | sed "s/0.0.0.0/$ip/")

json_data=$(
    cat <<EOF
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "list_channels",
    "params": [
        {
            "peer_id": "$f_peer_id"
        }
    ]
}
EOF
)

curl -sS --location 'http://18.167.71.41:8231' --header 'Content-Type: application/json' --data "$json_data" | jq '.result'

payment_preimage="0x$(openssl rand -hex 32)"

response=$(curl -sS --location 'http://43.199.108.57:8237' \
    --header 'Content-Type: application/json' \
    --data "$(
        cat <<EOF
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [{
        "amount": "0x3b9aca00",
        "currency": "Fibt",
        "description": "test invoice generated by node g",
        "expiry": "0xe10",
        "final_cltv": "0x28",
        "payment_preimage": "$payment_preimage",
        "hash_algorithm": "sha256"
    }]
}
EOF
    )")

echo "$response" | jq -r '.result'
invoice_address=$(echo "$response" | jq -r '.result.invoice_address')

curl -sS --location 'http://18.167.71.41:8231' --header 'Content-Type: application/json' --data "$(
    cat <<EOF
{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "send_payment",
    "params": [{
        "invoice": "$invoice_address"
    }]
}
EOF
)" | jq -r

sleep 5

curl -sS --location 'http://18.167.71.41:8231' --header 'Content-Type: application/json' --data "$json_data" | jq '.result'
